// SET USER INFO



//Signup
export const SIGNUP_PATIENT_REQUEST = 'SIGNUP_PATIENT_REQUEST';
export const SIGNUP_PATIENT_SUCCESS = 'SIGNUP_PATIENT_SUCCESS';
export const SIGNUP_PATIENT_FAIL = 'SIGNUP_PATIENT_FAIL';

// LOGIN
// export const LOGIN_EMAIL_REQUEST = 'LOGIN_EMAIL_REQUEST';
// export const LOGIN_EMAIL_SUCCESS = 'LOGIN_EMAIL_SUCCESS';
// export const LOGIN_EMAIL_FAIL = 'LOGIN_EMAIL_FAIL';

// FORGOT PASSWORD
// export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
// export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
// export const FORGOT_PASSWORD_FAIL = 'FORGOT_PASSWORD_FAIL';
